### ISSUE TITLE
GUID

### ISSUE THREAD

**Issue by jgillis** [casadi/fmu_compiler#1]
Universal fmus fail to load: `[vdp:error] fmi2Instantiate: Wrong GUID {b8ce82f1-07c8-4139-9a24-ec6c2b483c64}. Expected {120c62d2-a7ea-474b-a370-7d8ec154ee0e}.`

**Comment by jgillis** [comment]
GUIDS are different in manylinux and windows -> move generation to a separate task

**Comment by jaeandersson** [comment]
You can also generate separate FMUs, different ones for Linux/Mac/Linux. Then this is a non-issue
